services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 30s
      timeout: 20s
      retries: 2
      start_period: 20s