networks:
  jenkins:
    driver: bridge
services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: always
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./jenkins-docker-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
    command: --storage-driver=overlay2

  jenkins-blueocean:
    image: jenkins-blueocean:2.401.1-1
    build: .
    container_name: jenkins-blueocean
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins-docker-certs:/certs/client:ro
      - ./jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    restart: always
